"use client";
import "./globals.css";
import { Providers } from "@/store/provider";
import Header from "@/components/ui/Header/Header";
import Footer from "@/components/ui/Footer/Footer";
import { CookiesProvider } from "react-cookie";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="flex flex-col">
        <Providers>
          <CookiesProvider>
            <Header />
            <div className="min-h-screen">{children}</div>
            <Footer />
          </CookiesProvider>
        </Providers>
      </body>
    </html>
  );
}
