import "./globals.css";
import { Providers } from "@/store/provider";
import Header from "@/components/ui/Header/Header";
import Hero from "@/components/ui/Hero/Hero";
import Footer from "@/components/ui/Footer/Footer";

export const metadata = {
  title: "Interactive Nerd",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="flex flex-col">
        <Providers>
          <Header />
          <Hero />

          <div className="min-h-screen">{children}</div>
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
