"use client";
import "./globals.css";
import { Providers } from "@/store/provider";
import Header from "@/components/ui/Header/Header";
import Footer from "@/components/ui/Footer/Footer";
import { CookiesProvider } from "react-cookie";
import { UrlContext } from "@/context/UrlContext";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="flex flex-col">
        <Providers>
          <CookiesProvider>
            <UrlContext.Provider value={process.env.NEXT_PUBLIC_API_URL}>
              <Header />
              <div className="min-h-screen">{children}</div>
              <Footer />
            </UrlContext.Provider>
          </CookiesProvider>
        </Providers>
      </body>
    </html>
  );
}
